# Generated by Django 5.1.1 on 2024-10-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_students_stu_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.CharField(max_length=50)),
                ('stu_query', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='stu_contact',
            field=models.IntegerField(),
        ),
    ]
