# Generated by Django 5.1.1 on 2024-10-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_query_alter_students_stu_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='myQuery',
        ),
    ]
